# What can you publish? {#whattowrite}

**Just about anything!**

As an early career researcher, you will have a body of work from your thesis that you may have already published, or be in the process of publishing. These likely contain a number of data chapters that will be published as a series of papers in scientific journals. However, it's worth reflecting here about what it is possible to publish and how this might complement your existing and future publications, as well as increasing your publication portfolio with which to further your career. Certainly, having more publications is likely to increase your visibility in your community, as well as giving you more practice in academic writing.

## Reviews
See review articles [elsewhere](review.html).


## Commentaries or Opinion pieces
Your opinion is important, or at least as important as anyone else's. It can be very useful to publish a commentary on a precently published paper in your field. Inside/Outside of JEB.

This could also be a political stance that you have adopted inside your area of biological sciences (e.g. language, covid, racism, colonialism, etc.).

## Letters
These are generally very short pieces that you can write, often to high profile journals with letters pages. They can be used to raise the profile of all sorts of issues within your subject area or profession.

## Editorials
You are unlikely to be able to publish an editorial without first being an editor, but there may be a potential for you to become an editor, associate editor or junior editor in a number of society or publishers' journals. Once in position, the editorial is a powerful place to launch your opinion to subscribers.

