# What is the Impact Factor of a journal, and why is it so important? {#impactfactor}

The impact factor of a journal relates to the number of times each publication from the journal gets cited in the two years preceding the date of the Impact Factor (IF) (Equation \@ref(eq:Impact-Factor)). Thus, if you are thinking of publishing in a journal that has an IF of 1 you might expect that In the two years following the publication of your article you may get one citation. But this is not necessarily true for your paper. As discussed elsewhere you might be very good at publicising your work and have it extensively cited. One or two extensively cited papers might even change the impact factor of the journal without too many publications per year. As IFs are calculated on average for all papers published in that journal. If on the other hand you are thinking of publishing your article in a journal that has an IF of 5, you might expect that your article will be cited 5 times more than if you published in the first journal. 

It’s a relatively simple calculation as seen in equation \@ref(eq:Impact-Factor):


\begin{equation*} 
\frac{Sigma  citations  in  journal X for  year Y}{(Number of publications in journal X for year Y-1) + (Number of publications in journal X for year Y-2)}\left( \int_{a}^{x} f(u)\,du\right)=f(x)
(\#eq:Impact-Factor)
\end{equation*} 


Because all citations for year Y are needed before the IF can be calculated for each journal, IF for the preceding two years is typically not released until June of Y+1. 

Impact Factor is calculated by Thomson Reuters based on their Science Citation Index now called the [Web of Science](https://www.webofknowledge.com/). This means that if your journal is not even listed in the Web of Science then it will not have any Impact Factor. The [Web of Science](https://www.webofknowledge.com/) is continually policing the quality of the journals but it includes and this means from time to time channels are excluded. This tends to happen at the lower end of the Impact Factor scale. But recently it happened to some very well known journals and there was a big stink. You can read more about this [here](https://retractionwatch.com/2020/07/13/stunned-very-confused-two-more-journals-push-back-against-impact-factor-suppression/).

Note that there is a large conflict of interest here. A publisher, Thomson Reuters, owns the [Web of Science](https://www.webofknowledge.com/) and that's the means to decide whether or not a publication can get an Impact Factor. Is it more likely that journals published by Thomson Reuters will be included in the Web of Science? Previously the Science Citation Index was a not-for-profit organisation. Now the organisation that is used by many of our employers in their means of evaluating our effectiveness is owned by a private company. This is certainly cause for concern. There is a group of people who are trying to replace Impact Factor with a group of other metrics, so perhaps by the time you read this Impact Factor will no longer be relevant. If you're interested read more [here](https://www.nature.com/articles/d41586-019-01643-3).

Do remember that there are a number of other citation indices including Scopus and Google Scholar. Google Scholar doesn't currently calculate the Impact Factor for all journals, only the top 100. 

## From a simple score to a way of life

When IF was originally devised, it wasn’t supposed to govern the lives of academics. It was a calculation for librarians to help them decide which journals to keep and which to ditch under ever constrained budgets (caused by publishers' ever increasing prices). But along the way, this very simple index is now considered by many people to be a measure of quality, prestige and even academic success [@garfield1999journal]. Many people have highlighted how wrong these beliefs are (see here and here), but the growing trouble is that not only have many academics been misled, but so have administrators responsible for hiring and promotions. 

In a paper by McKiernan et al [-@mckiernan2019use], they found that this metric features in the guidelines of many university panels responsible for the fate of academics jobs and therefore lives. Worryingly, many of these institutions don’t actually talk about what IF measures. Instead they equate it with values and qualities that it certainly does not represent. Thus you may find that your career is influenced by a simple metric that almost all who use it don’t actually understand what it means. The undue influence on lives of scientists that IF has led directly to the San Francisco Declaration on Research Assessment (known as DORA) in which many institutions and publishers signed up to. You should read this very simple declaration and find out whether your institution is a signatory.

## What can you do if you publish a journal with high IF?

Very high ranking journals for Impact Factor are publications like Cell, Nature, Science and PNAS. This is because these publications are read by a very great number of people, and so are widely cited. Articles that get published in them receive a lot of attention from the press and media. This results in the prestige that a hiring institution might be looking for. If your academics publish in this journal, your institution may well receive lots of positive publicity. In some countries, notably China, there may be a cash incentive towards publishing in a journal with a high IF [@quan2017publish].

One frightening trend that we are seeing in biological sciences is that the higher the Impact Factor the more the journal will charge you to publish in it. At the time of writing in November 2020 nature has just announced that they will charge $9500 to publish in the highly-ranked journal (see [part 5](openaccess.html). This is more money than it cost to publish in any other journal at the moment. 

## Why is it so important?

Academics are measured by their productivity but also about the quality of their output. Because there are so many different academic disciplines the bean pushers who administer us need some way of ranking academics against each other. This is why they use the Impact Factor of the journals that the academic publishing in order to determine the quality of their output. Even though there are other metrics of the actual quality of an academic, most administrators continue to cling to IF and their beliefs of what it stands for (see blog post here).

Some countries reward their academics if they publish in high ranking journals. This can result in a salary bonus. It may also help with promotion, getting tenure or even just getting an interview for a job. If you're going to publish and you want a career in academia then you need to be aware of Impact Factors and what they mean to different stakeholders. 

Many people will complain that their particular sub-discipline has a range of very low ranking journals with low impact factors. Others complain that journals with high impact factors tend to be edited by an old boys club that facilitates the members. In some cases like PNAS this is certainly true. 

## Editors try to increase IF
It's important to remember that editors care about Impact Factor [see @ioannidis2019user]. There are several reasons for this. Firstly, as the editor the impact factor of the journal can be used (by the publisher or society) as a simple measure of how well the editor is doing. Secondly, the higher the impact factor of the journal, the better quality of submissions of manuscripts to publish. Being the editor of a journal with a low (or no) impact factor can result in a lot of mediocre manuscripts that are being submitted. Poor manuscripts take up much more time than good ones: more rounds of review, more disagreements among reviewers and more time spent making editorial decisions. Thus, by increasing the IF of the journal that you edit, you are likely to increase both the number of submissions (allowing you to reject more poor ones) and retain better ones.

All this means that if they think your paper will not garner the same or more citations in two years as the current Impact Factor they are likely to reject it often without even sending it out to review. Editors also have been known to manipulate impact factors and there are a number of established ways of doing this [see @metze2010bureaucrats; @martin2016editors]: 

1. Ask authors to cite publications from your journal published within the last 2 years. 
1. Ask reviewers to suggest publications from your journal published within the last two years to authors on which their review is conducted.
1. Encourage submission papers from laboratories with high output and citation rates
1. Reject papers that are likely to have no citations. This effectively reduces the size of the denominator in the above equation 
1. Publishing issues in January means they have a maximum period of the year to get cited. This is now being inflated to having issues published online well ahead of the January date all the time gathering citations. 
1. Encourage review articles
1. Editorials that cite every paper in the journal. This tactic is frequently used in special issues. 

Just like any metric, Impact Factor is liable for abuse. You need to be aware of how IF is used and abused by many people in the academic community. 

## Push back against IF
One very simple way that you can push back is to calculate IF scores for your papers and show how they relate to the IF of the journal that you publish in. In this way you are simply comparing your actual citations in the 2 years after your paper is published with the mean for the journal. There is a good chance that you generally get more citations than the mean for the journal, and with some statistics you can convincingly show that your citations are significantly higher than the IF. For this to be true, you might need to help your work get cited. [That’s the subject of another chapter](citations.html).
