# Preprints {#preprints2}

## What are Preprints?

So far in this book I have explained about the process of peer review how important this is and why it's the gold standard in science. Preprints came to us from the world of physics. An academic world that is moving so quickly that many inside it don't want to wait for peer review before making their work public.

Preprints do a little more than this because it not only makes the work public but allows it to be read by more peers. Many consider it as a kind of open peer-review system. 

In biological sciences the most prominent preprint server is called [bioRxiv](https://www.biorxiv.org/). 

## Why might you want to post a preprint?

One of the advantages of posting a preprint is that it gets a [DOI (digital object identifier)](https://www.doi.org/). You can then use this DOI to refer to your work even though it is not published in a peer review journal. 

For example imagine that you've just finished your thesis and only one of your chapters is published. How can you show to prospective employers how good your work is? Or if you are applying for money how can you refer to your work even though it's not published? A preprint is a simple solution to this problem.

Other benefits include having a wider scope of peer reviewers. if you know that in your subject area there are many people who may want to comment on your work constructively then this would be an opportunity to give them access. Importantly in a preprint because it has a DOI your work is not vulnerable to theft. It also allows you to stake your claim on the work that you've already done even though there may be a lag time between this and it coming out in a journal with full peer review.

If you do want feedback on a manuscript that you have posted as a preprint then you will need to tell people about it. A good example of this would be after providing a talk, or a poster, at a conference you might show a QR code where people can read your manuscript as a preprint. you can also publicise it to your community on social networks like Twitter. 

If you get lots of feedback on your manuscript then you should expect to incorporate it. So be careful what you wish for, because you could be opening yourself up for a lot of comments.

## Upload newer versions

If you, or others, spot errors in your preprint, or you find new literature to cite, you can update your manuscript with a new version. Indeed you should do this for as long as your preprint remains active. Once published, make sure that there is a pointer from your preprint to the published version. 

## Will you have to post a preprint?

This field is moving quickly. In December 2020 at least one journal (eLife ‘publish then review’) announced that they won’t accept a submission until a preprint has been registered. Thus all reviews are made on preprints. Other journals, like PLoS, are announcing in house preprint servers. You should expect this area to rapidly change in the coming years, so no matter when you are reading this, you are more likely than ever to need to submit a preprint. 

At the time of writing, there are still some journals that make it a condition of submission that there is no preprint. Make sure you check within your target journal list.

## If we all post preprints, do we really need peer review?

As far back as 2002, William Arms [@arms2002what] suggested that openly soliciting comments on the web might be an alternative for peer review of scholarly articles. Sixteen years later, this has come to pass in the form of preprints. 

There is a growing trend for publishing preprints. Preprints are simply manuscripts that are submitted to an online server and available for all to view. Physicists started first with this phenomenon, but biologists have been hot on their heels and there are now a number of prominent preprint archives including [BioRxiv](https://www.biorxiv.org/).

Each of these sites maintains the open access manuscripts, and allows other users to post comments (partial or complete peer-reviews) of these online manuscripts.

There are problems in the world of publishing. Mostly related to the greed of publishers who demand large sums of money for content that they do not pay to produce, but charge for access. We must look for alternatives to the current model, so could we replace publishing with an open platform like BioRxiv?

## Could these comments pages really replace peer review?

Peer review is held as a gold standard in scientific publishing, and there’s certainly a lot to that. It ensures that published material has been read and its contents assessed independently. But peer review is fallible, because scientists are humans.

- Not all reviewers can assess all parts of a paper, especially papers that cover several disciplines
- Not all editors will choose reviewers that are independent and objective. Depending on the framework set up for the journal, friendly reviewers can be chosen or critical reviews removed. Perhaps the inverse is more common, although you are less likely to see these manuscripts published.
- Poor peer review is a growing problem.
- Lastly, and not least, there is an increasing difficulty in finding peers who are prepared to review manuscripts. (See the Perry et al [-@perry2012peer] editorial, which was a plea to the herpetological community to accept reviewing as a necessary duty).

In 2003, Stefano Mizzaro proposed changing peer review to the format that we now see in preprint journals. Let every reader become a reviewer. Another take on this same theme is provided by Heesen and Bright [@heesen2020peer] who argue for a more subtle change in the date of publication (prior to peer review as seen in preprints) instead of after peer review. Here their emphasis is on removing the wasted time spent reviewing and then rejecting manuscripts that will never be published. Their discourse is very persuasive, yet given that both models currently exist we need more ideas on how we could drive a preprint model forwards. More ideas do exist, and I encourage you to explore those proposed in a special issue edited by Kriegeskorte et al [-@kriegeskorte2012emerging].

In the preprint model, the first three problems (above) might all be overcome as no-one chooses the reviewers. Instead they choose themselves, and are motivated to do the work. Their competence to cover all aspects of the manuscript is not assured, but one assumes that independently motivated reviewers will only comment on parts that they are able to assess.

All of this is very good, but will people actually read and comment?
A quick look at the sites will tell you a lot about the level of reviewing that is currently going on in biosciences preprints. A quick look through the top 10 articles on BioRxiv zoology section confirmed my suspicions. Plenty of tweets about the articles, but none of them had any comments. Indeed, a further trawl through PeerJ Preprints also found no comments. 

Further, I’d suggest a greater move to this culture might produce comments for well known labs, a certain amount of trolling for labs with ongoing disputes or rivalries, making this kind of comment review a sort of trial by popularity. But I don’t see a situation where potential reviewers will take time-out once a week (for example) and hunt for manuscripts that have received no comments. It seems far more likely that the authors will have reciprocal agreements with other groups to review each other’s manuscripts. This nepotistic tendency then puts us back into the area of peer review that we’ve been working hard to overcome now for sometime (double-blind reviewing, editors' codes of ethics, etc.). 

## When should evaluation end?

One point raised many times in the special issue edited by Kriegeskorte et al [-@kriegeskorte2012emerging] is that evaluation should be open ended: __ongoing evaluation__. There was a consensus to see reviewers continue to question the contents of papers long after publication. But these authors don’t appear to have a realistic perspective on the time of authors to defend their work. Imagine the effort that you currently put into a rebuttal letter (see chapter above). Now consider that your first rebuttal might come after a few months, and then you need to compose another after a few years. Perhaps you are the only author still working (especially if it is the work of students). Perhaps all of your co-authors are dead! Suddenly you are called upon to defend your work, potentially decades after completion. Can you do it? Would you want to do it? What would be the consequences of not doing it?

While I am regularly the first in the queue to criticise the current peer review system. I am also very grateful that publication represents a line in the sand under which I won’t have to continue working on a project. In a world in which I had continually documented every step of every experiment ([see part 3](methods.html)), I can imagine that it is potentially possible to find a defence for every step in a protocol. But the painstaking nature and time involved in going through old work would be an added burden that I cannot welcome with any enthusiasm. Personally, in a world when I have the option of working on a new project or endlessly and repeatedly defending old ones, I’d pick the new project every time. 

## Are preprints published?

As they each have a DOI ([Digital Object Identifier](doi.html)), they are in their own way already published.

Another point is that these articles are picking up citations. And there is a new concern that these articles are being cited, even when they are subsequently available through a published journal. This is one of my personal concerns with using a preprint service. I’m happy to put the paper out there for public comment, but the idea that it’ll remain there and that readers won’t necessarily be redirected to the peer-reviewed version does concern me.

Another question is what happens to manuscripts that are placed on preprint servers, are then sent out for review but not published because they are fundamentally flawed? It’s not as if the reviews are not made, but there is no automatic link to the reviews by the journal that conducted them.

Whether or not there is a paper inflation, there is certainly an ever increasing number of papers. The rejection rate is not insignificant, and while many of the papers are not rejected because they are flawed (they may well go on to be published in another journal), there are certainly a lot of manuscripts out there with fundamental flaws. These are often sent for peer review, but those reviews pointing out the errors won’t necessarily make it back to the comments page on the preprint server. I think that this is a serious problem. The reviewers have spent time and effort and the very reason they do this is so that manuscripts with fundamental flaws don’t find their way into the literature. However, preprint servers have, perhaps unwittingly, found a loophole that allows manuscripts that are not scientifically robust a backdoor to citations. 

## But if they are fundamentally flawed, shouldn’t everyone be able to spot it?

No. Reviewers are chosen with great care because the area is in their particular domain. They have insights that not everyone will be aware of and these are an important aspect of the purpose of peer review.

I edit for the journal PeerJ. Although there can be various reasons to be rejected from PeerJ, normally it means that your paper is not scientifically sound. As PeerJ has no selection for impact, rejection does not normally mean that it can be simply submitted to another journal. I have noticed that manuscripts that I have rejected from PeerJ are still available as PeerJ-preprints without any comment on their failure to go through peer review. In my opinion, this is not good as it essentially ignores the input given by both reviewers and editors. The article appears as if it has had no comments or attention, when this is not the case. In a system where we move to relying more on preprints, why would we want to ignore chosen peer reviewers for whom this article was within their specialist area?

Moreover, I note that the preprint in question is also receiving citations (according to Google Scholar), again raising concerns that rejection by peer review is not a hurdle to entering the scientific literature.

## In my opinion, comments pages won’t replace peer review.

If we end up abandoning our current way of publishing in favour of a comments page, I think that we’ll all be worse off. Much more likely is that increasing numbers of journals will require preprints as well as open peer review, hopefully leaning towards a more open and transparent publishing experience.

We simply need to overcome the vanity of having our manuscripts set out in a pretty way. If you are a postgraduate student reading this, then you are the first who will suffer from the mistakes of your community over the past 40 years. But you can also be the solution, mostly because you will be so badly in need of a solution that the system has to change for academia to survive. Us oldies will eventually be happy to accept unformatted manuscripts as the way science is presented, I think we’ll be able to move on without the involvement and the exorbitant costs that the publishers extort from us. What will be a bigger challenge is to topple the provaledge from those who control STEM with the editorial roles. The temptation will always be for the younger elite to take on that privilege, to benefit as previous generations of academics have. Breaking that circle of abuse will require widespread adoption of new rules for peer review.
