# Should you submit your manuscript as a preprint? {#preprint.html}

Later on in the book ([part 5](preprints2.html)) there is a chapter that deals with preprints, explaining what they are and how they function - essentially a place for manuscripts prior to peer review. However, the question of whether or not you should submit your paper as a preprint is relevant now. Essentially, there is no right or wrong answer, and it’s entirely up to you, your advisor and your team of authors. 

Here are some reasons for and against submitting your manuscript as a preprint:

## For:

- Your manuscript needs to be cited by another that you are submitting and you are worried that the peer review process will take too long
- You are aware that another lab is working on a similar project and are worried that submitting to peer review will scoop your findings. 
- Your work has immediacy that it might not have after (potentially) 3 months of peer review. It may be that by releasing your preprint you can contribute to an ongoing debate that otherwise you’ll potentially miss.
- You are concerned that you’ve missed something important or perhaps analysed something in a novel way that others might be able to help with. You want this chance at feedback before submitting to peer review.
- Your manuscript crashed out of peer review with comments that you felt were unfair or unsubstantiated. You are looking for more balanced comments.
- In the above case, you might be able to use your preprint as leverage to persuade an editor that your contribution should be fast tracked into their journal.
- If you can generate enough buzz and positive feedback, you might be able to get leverage on an editor for submission to a journal with a higher impact factor.
- You have a working group that you actively want to share your publication with, even before it is published

## Against:

- Any of your co-authors don’t want the manuscript submitted as a preprint before peer review
- There is a real chance that others can use the access to your work and publish it before you

I can’t really come up with a lot of reasons against submitting a preprint. This is possibly because I’m broadly in favour of preprints and see that there is value there. However, I’ve done it with only a fraction of papers submitted in the last 5 years. Why? 

My experience of preprints is disappointing. Although these get widely shared on social media, and garner a large number of downloads, they don’t generate comments from colleagues. Even when we have sent links of preprints to colleagues asking directly for feedback, we’ve received nothing. Looking through a random selection of preprints on PeerJ, I found no comments, suggesting no feedback for any of them. 

At this point, I should say that I have not (yet) made any public comments on a preprint. When I have looked at preprints, I (generally) have downloaded them in order to look at some of the details (often the methods or analyses), when there’s a dearth of peer reviewed (published) material. There are a few references to preprints in this book. I’ll replace them if I find that they have been published. But what should I do if the published version doesn’t contain the point that I’m citing on? In this case, I’ll delete the citation and no longer make the claim because there is the chance that the result did not stand up to the rigours of peer review.
