# What to expect from your reviews {#reviewcomments}

## What are peer reviewers asked to do?
The peer review report consists of three major parts:

### The review
Peer reviewers should sum up the manuscripts in their own words to demonstrate that they have understood the contents. This is important because being able to summarise what you have read demonstrates the reviewer’s comprehension. If the reviewer gets this summary wrong, then it is either a flag to the editor that they lacked the necessary comprehension to make their review meaningful. Or, because there are two sides to comprehension, a flag to the authors that they failed to write their manuscript in a way that made it easy for the reader to comprehend. 

The reviewer should then provide a general critique including positive and any negative aspects of the manuscript. They should provide detailed information on exactly how the manuscript should be improved, including any significant literature that might be missing from the manuscript. Lastly, they can provide a list of minor comments along the length of the manuscript that require further attention from the authors. When I undertake this last part, I tend to do it with page and line numbers (which is one reason why submitting a manuscript with line numbers is so important. If the minor comments get too numerous, then I tend to stick with major comments.


### The confidential comments to the editor
I'm not a big fan of confidential comments but sometimes they are warranted. The reviewers are provided with a box where they can write to the editor without text being seen by the authors.

### Their opinion of what the editorial decision should be
In many journals, the reviews are directly asked whether the manuscript should be rejected and resubmitted major or minor revisions. Personally I don't think that reviewers should be asked these questions as this is a decision for the editor after having read the reviewers comments and the manuscript.

## What are reviewers not asked to do?

### Peer review is not a trial by committee
Those of you who have experienced manuscripts being critiqued at a book journal club will know that there are very few published papers that leave a journal club without having many negative critical comments. Instead peer review is conducted by an individual, on their own and with their own personal limitations. Peer reviewers are forbidden from sharing the contents of a manuscript with others, without permission from the editor.

### Correct English grammar
As mentioned in ([Part II](foreign.html)), it's not the job of a reviewer to correct any faulty grammar on a manuscript. similarly it is not up to the reviewer to correct stylistic aspects of the manuscript. 

I have noted that some reviewers have become quite obsessive about things like the Oxford comma - insisting that the Oxford comma should be inserted at every possible juncture. Instead I think that it is important for authors to keep their own voices. See chapter in part 2.

### Tell the authors to cite their papers
Sadly, this is something that a lot of peer reviewers do. At most, the reviewers’ own work can be cited, but only when relevant.

### Tell them to cite other papers from the journal
This also happens [see chapter on Impact Factor](impactfactor.html) often at the request of the editor.

### Justify comments with their own beliefs and opinions 
Peer review should always be an objective critique of a manuscript. It's not really the place of the reviewer to express their opinion or their beliefs about a particular study that they are reviewing. 

Reviewers should stick to the evidence that they're provided with. If they are not provided with sufficient evidence then they should draw attention to the lack of information rather than extrapolate to what they believe might be the case. 

Authors should be provided the benefit of the doubt and opportunity to respond to such criticisms especially when information is missing. It's unfair for reviewers to act as judge and jury. This is the job of the editor. 

### Assess aspects of the manuscript that are beyond their competence
Some manuscripts are cross-cutting across several subjects or may contain analyses outside it with the experience of a reviewer. In these cases reviewers should not attempt to review areas that are beyond their competence. Instead they should bring these aspects to the attention of the editor when they are submitting their review.

### Ignore what is good
Is often thought that peer review provides only negative criticism. This should not be the case as peer reviewers should also be able to accentuate the positive aspects of manuscripts that they read. Even if a manuscript is not considered publishable the positive attributes should be bought the attention of the editors as well as those that are negative.

It is important for authors to understand what aspects of their manuscript are good. This kind of feedback from peer review will influence future versions of this manuscript as well as future studies from these research groups.

