# Once your paper is accepted {#accepted}

The day your paper is accepted, tell your advisor and co-authors. If they are in the same physical location as you then buy a cake and celebrate with them at tea time. If cake isn’t your thing, then find another appropriate treat for you and your co-authors. It’s a great achievement and something you should share together. If you aren’t in the same location then make a plan for next time you meet together, even if that’s only online. 

Remember to make sure that all of your coauthors have a copy of the accepted version of the manuscript. Sometimes referred to as a postprint, you and your co-authors should submit this to your institutional repository so that the article can be reached as [Green Open Access](openaccess.html) by anyone who is interested in reading it.

The next step in the publishing process once your paper has been accepted is that it will go for type setting. Depending on the journal and the publisher this process can proceed in several ways. Typically you will receive a notification that your paper proofs already and that you need to check them within 48 hours. 

If you haven't checked proofs before then it is important that you read the instructions from the publishers carefully. They should tell you exactly what to do and if you are unsure about anything then talk to your advisor.

Typically the publishers will send you a set of queries that relate to your proofs. They always ask you to check every author's name and affiliation. Other typical errors are that there are citations in the text that are not in the references. Or that there's literature in the references that are not cited.

The process of checking the proofs is very important. Errors can creep in during the type setting stage. Pay special attention to the tables table legends and figure legends. 

You may also have the opportunity to change the size or orientation of figures if it looks like they are not well presented in the proof. Especially if the journal prints into columns they may choose to put your figure in one column instead of two. Another option is to have your figure in landscape across the whole page. Journals are generally pushed for space and so may refuse some requests for more room for larger figures. But you might get lucky if you make a good case.

## Take your time with proofs
Probably the easiest way of doing proofs is to print them out and go through them with a pencil first. This allows you to take your time and you're more likely to spot errors this way than on the screen. 

You should allow your advisor and co-authors to look at the proofs before resubmitting. I usually suggest that you make all your own corrections first before sending them around. 

## Once you have a publication date
Once your paper is published you have an opportunity to publicise it yourself. There are lots of different ways to do this, [see the next chapter](citations.html). 

## On the day you publish
This is a great opportunity to contact all the people who helped you in your study and send them a PDF of your paper. The easiest way to do this is to go to the acknowledgements section and write an email that includes everyone that is mentioned in the acknowledgements. write them a nice email in which you thank them for their help and explain briefly the significance of the paper. 

It is a very good idea to keep all of these people informed about your publication as soon as it is published. You really want them to hear about it from you first and not from somebody else. This includes contacting any authorities that have issued permits. You may also want to contact funders. 
