# Is Open Access good? {#openaccess}
Open access appears to be a great initiative that acknowledges that everything should be free to view. Neither scientists nor the public that fund them should be barred from accessing the knowledge that they produce. What could be wrong with this?

## So what is open access?
I have covered the many different kinds of Open Access (OA) elsewhere in this book ([see part 4](openaccess1.html)). Here I concentrate on the fiscal implication of OA. Someone needs to pay for the work done. Who should pay and how?

Open access is probably one of the best scams that the publishers have come up with to date. Now the scientists pay for making their own content open for anyone to read. They pay a once off fee to the publishers to typeset the manuscript and host it on their site without a paywall. And how much do the publishers want for this service. Prices start from USD 1000 and go up to around USD 12 000. More frightening, and evidence that publishers are simply taking advantage of scientists, is that prices increase with the Impact Factor of the journal [@gray2020sorry], although the costs involved to the publisher remain static. 

The money comes from the funds that would otherwise be reserved for conducting science. So now the money for research goes directly into the pockets of the publishers upfront. Money that ultimately comes from you as tax-payers goes directly to publishers. Still happy?

## So does that mean that these journals are now free?
Mostly no. The majority OA model ([hybrid OA](openaccess1.html)) means that a minority of articles in these journals are free, but the universities are expected to subscribe to those same journals at ever increasing prices because much of the rest of the content is still behind the [paywall](paywall.html). This is because most authors cannot afford to pay the exorbitant fees charged by the journals (although some countries now have this payment as mandatory - PlanS, they and their scientists are still in a minority). There are some journals that are entirely open access ([gold OA](openaccess1.html)). These are (almost) exclusively online and have never been part of traditional packages that university libraries spend so much of their budget on. Hence the fact that they are entirely free does not impact library budgets. As a scientist, it will make an overall increase to papers that you can access. 

But paying for open access has not reduced the cost of access to scientific journals for libraries. This cost constantly goes up. [Hybrid OA](openaccess1.html) was a brilliant scam dreamt up by the publishers, because for much of this content we pay not twice but thrice [@buranyi2017staggeringly]!

## Nature Publishing - pay for review
The Nature Publishing Group has now proposed to go one step further: pay to submit your paper for review! In this new twist on the OA scam, the exclusive Nature publishing group is offering a discount to their new USD 11390 OA charge if you pay USD 2665 upfront before review. In this case, you will have the benefit of being told that your manuscript (most likely) is not publishable in Nature, but you can pay some more money to them in order to publish in one of their other journals. The most lowly (Nature Communications) would be another USD 3160, leaving you a few hundred dollars short than if you had submitted there originally. Or you could be rejected outright, and your USD 2665 is, of course, non-refundable. 

- Are Nature Publishing Group taking advantage of authors who aspire to publish in their exclusive titles? __Yes__. 
- Will they use the money to plough back to the benefit of science, scientists and the taxpayer? __No__. 
- Will the cover price of Nature go down when some of the articles inside are free to read? __No__.
- Will it be cheaper for libraries to subscribe to Nature? __No__.
- Will they line their pockets? __Yes__.
- Will they pay the scientists who conduct the peer review that they want to charge for? __No__.
- Can you see the common thread in the greed of publishers and the willingness to prey on scientists who need to publish in high IF journals for their career? If not, read [part 5](part5.html) again.

For a lot of academics there is a trade-off: vanity for cash. We know that for a lot of academics, their vanity will mean that they are prepared to find the money (even if it comes from their own pockets). However, for as long as enough are willing to pay, we will continue to be exploited. Instead, we really need a new model for publishing. For some academics they will be paying directly for a chance at [getting a job](jobinacademia.html) or [getting tenure](habilitation.html). The chances of these individuals reaching their goal from a privaledged institution then simply becomes reinforced. 

This is not a system that we should ever support, and one that we should do all we can to remove for the sake of transparency and equality in the greater [scientific project](beforeyoustart.html).


## A new model for publishing without publishers - the blockchain journal

### The problem
There are growing problems with publishers. Publishing has become very expensive for scientists, and the public who fund science. Many funders are now unwittingly funding publishers instead of science. I’ve discussed the history of scientific publishing before (here), and explained how commercial publishers have had a role right from the very beginning. This relationship continues to the present day, but while the origins saw learned societies commissioning publishers and then distributing their content, today the publishers have climbed into the driving seat, conceiving and owning many of the current journal titles. This is not to say that there are no scholarly societies that still dictate terms to publishers (The British Ecological Society, BES, do this very well), but they are few and far between, and even when society journals are involved, the goliath publishing companies easily outweigh any control that they might have once possessed (and I’m speaking from personal experience - [see part 5](paywall.html)).

The result is that publishers have become gigantic corporations that now dictate to the scientists that produce, edit and review all of the content. They charge incredibly high fees to anyone who might want to read the publicly funded content. The budgets of university libraries run into USD 100 000s just to access content. The result is that many universities can’t afford all of the content that their researchers need. Publicly funded content, and by that I mean that you dear reader are paying for the original science of the content in your taxes (yes, you all pay taxes, even if it’s only VAT), and then you pay a second time for the researchers (who themselves produced the content) to access the content. Who benefits from the fact that you pay twice? The publishers. Why aren’t you upset about this? Probably because you are unaware. But if you are upset, then join in the discussion to decide how to emancipate ourselves from the publishers who are merrily munching on through this publicly funded cash cow.

### What do publishers do?
The publishers would claim that they do an awful lot. All they really do is pay for the layout and printing of journals. These days ‘printing’ really means hosting electronic pdfs only, as there’s very little paper that’s printed, and you can be sure that paper subscribers now pay the extra cost of any additional fees. The layout from the manuscript (most often a MS Word doc) into a pdf does take some skill and talent, although nothing like what you might expect given how much the publishers charge. You can be sure that they don’t pay much for this service as almost all layout is done in India, Bangladesh, Sri Lanka, etc. Quality can be good, but more often quality control is completely lacking. Most authors have stories of how manuscripts have come back mangled, although my own impression is that the worst days appear to be over.

This is not to say that there are no skills in the publishing world. I also want to make it clear that I am not condemning all those employed by all publishing houses. I have interacted with many excellent staff at publishing houses that have some of the worst practices. It’s important to note that these staff do not get the fiscal benefit of the aggressive and unethical behaviour of their publishing companies. These profits are retained for the directors and shareholders. One might also question whether the sales reps of these companies who make deals with academic libraries don’t also receive unethical bonuses for their undisclosed financial arrangements. 

### What is publishing then?
Once publishers have ‘printed’ the manuscript, they ‘publish’ it by placing it behind a paywall on their website. I would be the first to admit that there are massive costs in doing this properly, and big journal companies have invested a lot to do this very well. The electronic hosting of journals is (in my opinion) truly excellent, except for that paywall. However, once they’ve set this system up, adding another 10 or 20 journals comes at practically no cost compared to the revenue that each one can be expected to gain.

To get behind that paywall, university libraries need to subscribe. Publishers bundle journals together and sell subscriptions at very high prices. If you are inside the university IP address, this access should be seamless. If you are outside, you might need to log in through your university’s library. There are other tactics for getting around a paywall ([see part 2](paywall.html)). 

So far, the publisher hasn’t produced any content. The scientific content has been produced by the scientist at the cost of the public purse. The editing and peer review ([see part 4](preprint.html)) has all been done by the scientists, which has also cost the public purse but has been completely free to the publisher. OK, so there are some small costs associated with manuscript handling software subscriptions that the publishers normally pay. The publisher has also paid for the typesetting (although they’ve done this as cheaply as possible - see above), and they’ve paid for the servers that distribute the pdfs maintaining that all important paywall. What else? Nothing else. Now they simply charge everyone to look at the content (and because it’s by subscription), actually charge everyone whether or not they are looking at the content. Bergstrom and Bergstrom [-@bergstrom2006economics] showed the difference between the costs of subscribing to society journals in 2005 was US$ 0.29 while for profit journals cost US$ 1.42, irrespective of any degree of quality. Fifteen years on, most society journals have now been captured by for profit publishers and now we all pay the higher price.

>'Open access is one of the best scams that publishers have come up with' 

But don't take my word for it. Read the excellent article by Stephen Buranyi [-@buranyi2017staggeringly]: Is the staggeringly profitable business of scientific publishing bad for science? In it, Buranyi makes the point that the profit margins of academic publishers are in excess of 40%. Something that even drug dealers, pimps and the mafia struggle to achieve. This situation seriously needs to change.
