# What are predatory journals? {#predatory}

Predatory journals are publications that purport to be from scholarly publishing houses, but have little or no editorial oversight or peer review. They exist in order to extract the Article Processing Charge (APC) that is so ubiquitous in Open Access journals. They continue to exist because publishing is moving towards APCs, and there is little difference between what they do and some supposedly ‘legitimate’ journals. For example, some definitions of predatory journals include that their APCs far exceed their publishing costs, but this can now certainly be said of some legitimate journals.

## If the line is so grey, how is it possible to tell whether or not a journal is predatory?
This is a surprisingly difficult question to answer. Predatory journals have become so sophisticated at what they do, that it can be very difficult to determine whether or not they are legitimate. Moreover, their electronically published journals can create new titles faster than the time that it takes to check that they are legitimate. An example of a publisher in the grey zone is Hindawi, that were once considered predatory but were later removed from Beall’s list. At the time of writing, I considered that Hindawi still had some questionable practices and so suggested continuing to avoid them. However, in a new twist, January 2021 Wiley (a well respected publisher) [acquired Hindawi for USD 298 million](https://scholarlykitchen.sspnet.org/2021/01/11/wiley-acquires-hindawi-interview/) (yes folks, your science is big business because of the big profits that Wiley expect to make out of you and your tax paying funders). This news goes to show how quickly the publishing world is reacting to the new world of OA, but also how publishers intend to dominate the market and maintain their stranglehold on scientific publishing. 

Most academics have an interaction with predatory journals through email. Indeed, the numbers of emails that academics are spammed with is astounding [@vandenberg2021solution], and while the best advice is to use a spam filter, I still find that too many legitimate emails got there too. These emails are not straight forward and seek to manipulate the reader into submitting a manuscript [@bett2020predatory]. Moreover, predatory journals target the most vulnerable in the community, poorer researchers who do not have English as their first language are deliberately targeted [@bett2020predatory, @lund2020analysis].

At the same time, legitimate journals have become increasingly predatory in their habits, and it’s difficult to tell them apart from predatory journals. There was a time when it was possible to categorically state that no journal will ever approach you with a general email that invites you to contribute. However, there are now several legitimate journals that send out unsolicited emails. Realistically then, in the current publishing world, there is a continuum from predatory to legitimate. It was not always this way, and that means that as an emerging researcher you are facing difficulties not faced by your advisor or other more senior academics. Not only do you need to avoid publishing in predatory journals, but you should also avoid citing their articles.

However, help is at hand. There are some definite ways that you can determine whether you are choosing a legitimate journal. Here are my 5 steps that you can take to safeguard your submission.

### To spot a predatory journal, use the following list in a stepwise fashion

1. Use an index. Web of Science and Scopus both curate contents of legitimate journals. If your journal of choice appears in one of these, then it is very likely to be legitimate. Note that Google Scholar includes many predatory journals, so please never use this to determine whether or not a journal is legitimate. Note also that it takes a journal several years to gain enough kudos to get accepted onto Web of Science and/or Scopus. Therefore, it can still be legitimate and not be there. We have previously discussed how to choose the right journal for your publication (see part 4). If the journal you want to publish in is not in Web of Science or Scopus, then proceed to the next step.
1. Ask your librarian. Librarians are fantastic sources as well as custodians of information, and journals are one of their key knowledge areas. Don’t hesitate to get in touch with your librarian and ask their advice. They are likely to be very well placed to respond to your request. They may also be guardians of granting APCs at your institution, so it is in their interest to make sure that these valuable monies don’t fall into the wrong hands.
1. Ask your advisor or an experienced colleague. It’s worth doing this with them so that you can see the steps that they follow. Given that steps 1 and 2 have already come back with uncertain answers, spreading your net more widely will help with step 4. However, be warned that there are increasing numbers of senior scientists that have been caught out by predatory journals, so checking their contributors is now no cut and dry way to differentiate between them and legitimate journals.
1. Who is on the editorial board? Journals publish names of their editors, associate editors and the editorial board. Look through these lists and see whether there are names that you recognise. If you know any of the people, you (or your advisor) can contact and ask them about the journal (they should be happy to respond). Be warned that it is easy to place someone’s name on a website, so unless they have personally told you, keep away.
1. Check against a known list. In the past, this might have been the first thing to do, but the number of predatory journals is proliferating so quickly that it’s hard for any list to keep up. Beall’s list retired in 2017. The next best list now has more than 3 times that. See here for an interview with the keeper of the new list, Simon Linacre. Sadly Simon’s list is behind a paywall, so you can’t expect to access it. One of the reasons why Beall gave up is that the new tactic for these publishers is to produce lots of new journals. Curating a list is real work and has implications for the publishers on it, hence you now need to pay to access an up to date list. There are more lists: Cabell's Predatory Journal Blacklist, Beall’s list, DOAJ delisted journals, Scopus discontinued sources, etc
1. If predatory journals are becoming more like legitimate journals, where’s the harm in publishing with them? 
1. Your reputation is important. As an emerging researcher, your publishing record is what many people will see first. It is all that is shown in your Google Scholar or ResearchGate profile. It’s your shop window or showroom. What prospective employers will want to see is that there are plenty of publications (appropriate for your career stage), and that they are in appropriate journals with good reputations. You might confuse having a good reputation with a high impact factor. The two need not be the same. High impact factor journals don’t accept all types of submission, and you may have data that simply doesn’t fit into one of their mandates. I would say that it’s still important to publish this, and there are many journals with good reputations where you can do so. Let’s leave discussion about the impact factor for another chapter.
  
The other reason why you would be best to avoid a predatory journal is that they attract very little in the way of scientific impact: few people will read or cite them (see article here). One thing that you definitely want for your work is for people to use it. To do this they must read and cite it. If you publish in a predatory journal, many scientists won’t even consider reading the content as it has not been, nor will it be, peer reviewed. Thus, unlike a preprint, it is not being openly offered to the community for review. 

Due to the ambiguity of whether or not these papers have been peer reviewed, I would also suggest that you do not cite publications that you think may be from predatory journals. You can use the same steps (above) to determine whether or not what you want to cite is from a legitimate journal.

## What do you do if you have already published in a journal that others consider predatory?

The first step would be to write to the publisher and withdraw the article. Whether or not you paid an APC, having it on their website is not good for your reputation. Beware, these journals don’t adhere to an ethical code, and so they might refuse to withdraw your paper. Or they may want to charge an additional fee to remove it (remember that they are in it for the money).

Do not cite the paper, or put it on your CV. You can easily remove such articles from your Google Scholar profile or ResearchGate. Don’t put it in your showroom.

Prepare a statement that explains how it happened. You may not have been responsible for the submission, or aware that the publication was from a predatory publisher. However, in time you are likely to forget the exact reasons. It would be a good idea to prepare a statement, so that if you are asked (for example in a job interview), you can explain how it happened. People can be very understanding when provided with an explanation, but if you say that you can’t remember or can’t give any details, then you may sound evasive.

Predatory publishing is a big problem in South Africa where 4246 papers have been published in 48 predatory journals: take a look at this article [@mouton2017extent]. And it’s not just publishing where the predators are lurking, they are also waiting to invite you to a conference (see [here](http://flakyc.blogspot.com/)). Your work is valuable to you and to your advisor, so please try to make sure that it doesn’t end up in the hands of a predator!
