# Are researchers writing more, is more better and who should be an author? {#publishmore}

The concept of some kind of ‘literature inflation’ in science has interested me for a while. The idiom ‘publish or perish’ suggests that researchers will increase their output in order to obtain positions and promotions. And if a researcher’s productivity is measured by their publication output, shouldn't we all be writing more papers?

Similarly, if we should all be writing more, then wouldn't some people start publishing two (or more) papers, when one would be adequate? This idea of ‘salami slicing’ to inflate outputs would be an understandable strategy if researchers were all trying to increase their output. Alternatively, the names of authors might be added to papers in which they did not make significant input via ghost authorship or hyperauthorship [see @cronin2001hyperauthorship for an interesting historical perspective]. 

A study by Fanelli and Larivière [-@fanelli2016researchers] has a new take on the above questions, by asking whether researchers are actually writing more papers now than they did 100 years ago. They used Web of Science to look for unique authors (more than half a million of them) and determine whether the first year of publication and the total number of publications resulted in an increasing trend.

## Researchers’ Individual Publication Rate Has Not Increased in a Century

Fanelli and Larivière’s [-@fanelli2016researchers] trend line for biology is very stable at around 5.5 publications whether you started publishing in 1900 or 2000 (note that earth science and chemistry do both increase dramatically). 

However, they found that the number of collaborators is increasing, and so they adjusted publication rates for co-authorship. Their finding was then that there is no increasing trend in researcher productivity. This then poses another question. Who are these people that are publishing so much more than 5.5 publications, and are they unfeasibly prolific?

## If we are all writing the same number of papers, are some authors unfeasibly prolific?

This was the question posed in a study that examined prolific authors in four fields of medicine [@wager2015too]. This publication piqued my interest as it turns out that they decided that researchers with more than 25 publications in a year were “unfeasibly prolific” as this would be the equivalent of “>1 publication per 10 working days”. Their angle was to suggest that publication fraud was likely, and that funders should be more circumspect when accepting researchers productivity as a metric. Looking back through the peer review of this article (which is a great aspect of many PeerJ articles), I’m astounded that only one reviewer questioned the premise that it’s unfeasible to author that number of papers in a year.

I have published >25 papers in a year, and I know other people who do this regularly. To me, there is no question that (a) it is possible and (b) that they really are the authors. Firstly, the idea that prolific authors constrain their activity to “working days” is naïve. Most will be working throughout a normal weekend, and working in the early morning and late evening. A hallmark of a prolific author would be emails early in the morning and/or late at night. This gives you an indication of their working hours, and how they are struggling to keep up with correspondence on top of writing papers. 

Authorship of a publication is often the result of several years of work. Thus, publications that I co-authored in 2017 frequently had research conducted in 2014 or earlier. For example, one of the publications, Measey et al [-@measey2017counting] is the product of aSCR work that started in 2009, funded in 2011 with fieldwork in 2012, and required the development of software for analysis by Ben Stevenson and colleagues [-@stevenson2015general], before it could be completed and submitted. Thus, from my perspective, when I look at authoring a lot of publications it reflects the activity of the initial concept for the work, raising of money, conducting the field work or experiment, analysing the data and then writing it up (with the subsequent submission and peer review time). Thus, publications in 2017 result from a lot of work done for more than 3 years. 

## Is writing a lot of papers a good strategy? 
This is a question of long standing, and one that you may find yourself asking at some point early on in your career. I'd suggest that the answer will be more about the sort of person that you are, or the lab culture you experience, over any strategy that you might consciously decide. If you tend toward perfectionism, this will likely result in fewer papers that (I hope) you'd consider to be of high quality. If on the other hand your desire were to finish projects and move on, you'd be more likely to tend toward more papers. It is clear that the current climate leads towards the latter strategy, with increasing numbers of early career researchers bewildered at the idea of increasing their publication metrics [@helmer2020what]. But what should you do?

Given that the 'best' personality type lies somewhere in the middle, you can decide for yourself whether you identify with one side more than the other. But which is the better strategy? Vincent Larivière and Rodrigo Costas [-@lariviere2016how] tried to answer this question by considering how many papers unique authors wrote and seeing how this relates to their share of authoring a paper in the top 1% of cited papers. Their result showed clearly that for researchers in the life sciences, writing a lot of papers was a good strategy if you started back in the 1980s. However, for those starting after 2009, the trend was reversed with those authors writing more papers less likely to have a smash hit paper (in the top 1% of cited papers). Maybe the time scale was too short to know. After all, if you started publishing in 2009 and had >20 papers by 2013 then you have been incredibly prolific. 

One aspect not considered Larivière and Costas [-@lariviere2016how] is that becoming known as a researcher who finishes work (resulting in a publication) is likely to make you more attractive to collaborators. Thus, publishing work is likely to get you invited to participate in more work. Obviously, quality plays a part in invitations to collaborative work too. Thus pulling the argument back to the centre ground. 

If you find yourself becoming preoccupied about which is the best strategy for you, I'd suggest that you get back to finishing what you were writing before you got distracted!

### Natural selection of bad science
In 2016, Smaldino and McElreath proposed that ever increasing numbers of publications not only leads to bad science, but is currently selected for in an academic environment where publishing is considered as a currency. They argued that the most productive laboratories will be rewarded with more grant funding, larger numbers of students, and that these students will learn about the methods and benefits of prolific publication. When these ‘offspring’ of the prolific lab look for jobs, they are more likely to be successful as they have more publications themselves. An academic environment that rewards increasing numbers of publications eventually selects towards methodologies that produce the greatest number of publishable results. To suggest that this leads to ‘bad science’ Smaldino and McElreath [-@smaldino2016natural] conducted an analysis in trends over time of statistical power in behavioural science publications. Over time, better science should be shown by researchers increasing their statistical power as this will provide studies with lower error rates. However, increasing the statistical power of experiments takes more time and resources, resulting in fewer publications. Their results, from review papers in social and behavioural sciences, suggested that between 1960 and 2011 there had been no trend toward increasing statistical power. Biological systems, whether they be academics in a department or grass growing in experimental pots, will respond to the rewards generated in that system. When grant funding bodies and academic institutions reward publishing as a behaviour, it is inevitable that the behaviour of researchers inside that system will respond by increasing their publication output. Moreover, if those institutions maintain increasing numbers of researchers in temporary positions, those individuals are further incentivised to become more productive to justify their continued contracts, or the possibility of obtaining a (more permanent) position elsewhere. Eventually, this negative feedback, or gameification of publishing metics, produces a dystopian and dysfunctional academic reality [@helmer2020what].

## At what rate is the literature increasing?
A study using several databases (Web of Science, Scopus, Dimensions and Microsoft Academic) back to the beginning of their collections at the start of scientific journals in the mid 1600s. They suggest that the inflation rate of scientific literature runs at 4.02%, such that the literature will double in 16.8 years [@bornmann2020growth]. This means that there is literally twice as much published in 2020 as there was in 2003. 

Although the early period of scientific publishing was notably slower than today, it is since the mid-1940s (following the end of “World War II”) that science has seen an exponential growth in productivity, with annual growth of 5.1%, and a doubling time of 13.8 years [@bornmann2020growth].

## If more is being published, will Impact Factors increase?
Yes. If the numbers of citations per paper remains constant, then the [Impact Factor](impactfactor.html) of journals should increase annually at 5%. My impression is that citations are increasing in papers as the literature increases, which suggests that Impact Factor will grow at a faster rate. 
